"""Tests for Markdown study-pack building and export."""

import json
import os
import re
import stat
from unittest.mock import patch

import pytest

from worsaga import secureio, studypack
from worsaga.cli import main
from worsaga.secureio import SecureWriteError
from worsaga.demo import DemoMoodleClient
from worsaga.sections import WeekNotFoundError
from worsaga.studypack import (
    PACK_RIGHTS_NOTICE,
    build_study_pack,
    study_pack_filename,
    write_study_pack,
)
from worsaga.redact import REDACTED


def _assert_provenance(markdown, *, course="ECON101", week="3", site=""):
    """Assert *markdown* opens with a complete provenance header.

    Every pack has to carry where it came from and what may be done with
    it, whether it was written to a file, printed to stdout, or returned
    inline through MCP — so every surface's test runs this.
    """
    from worsaga import __version__

    lines = markdown.split("\n")
    assert lines[0].startswith(f"> Generated by Worsaga {__version__} on ")
    # UTC, ISO 8601, ending in Z: a pack found on a shared machine later
    # must not be ambiguous about which day it was made.
    assert re.search(
        r"on \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\.$", lines[0]
    ), lines[0]
    assert lines[1] == f"> Source: {site} - {course}, week {week}."
    assert lines[2] == f"> {PACK_RIGHTS_NOTICE}"
    assert "do not redistribute without permission" in lines[2]
    assert lines[3] == ""


def _econ_course_id():
    for course in DemoMoodleClient().get_courses():
        if course.get("shortname") == "ECON101":
            return course["id"]
    raise AssertionError("demo dataset must include ECON101")


class _ManyFilesClient:
    """Offline client serving one section with N supported text files."""

    base_url = "https://moodle.example.com"

    def __init__(self, count, fullname="Testing 101"):
        self.fullname = fullname
        self.names = [f"reading-{i:02d}.txt" for i in range(count)]

    def get_courses(self):
        return [{"id": 1, "shortname": "T101", "fullname": self.fullname}]

    def get_course_contents(self, course_id):
        modules = [
            {
                "id": 100 + i,
                "name": name,
                "modname": "resource",
                "contents": [{
                    "type": "file",
                    "filename": name,
                    "fileurl": f"{self.base_url}/pluginfile.php/{name}",
                    "filesize": 64,
                    "timemodified": 1000,
                }],
            }
            for i, name in enumerate(self.names)
        ]
        return [{"id": 10, "section": 1, "name": "Week 1", "modules": modules}]

    def download_file(self, fileurl):
        name = fileurl.rsplit("/", 1)[-1]
        return f"Reading {name} discusses one distinct topic here.".encode()


class TestStudyPackFilename:
    def test_basic(self):
        assert study_pack_filename("ECON101", 3) == (
            "ECON101-week-3-study-pack.md"
        )

    def test_unsafe_characters_sanitized(self):
        name = study_pack_filename("a/b:c", "rev iew?")
        assert "/" not in name and ":" not in name and "?" not in name

    def test_empty_labels(self):
        assert study_pack_filename("", "") == "course-week-week-study-pack.md"


class TestBuildStudyPack:
    def test_demo_week3(self):
        client = DemoMoodleClient()
        result = build_study_pack(client, _econ_course_id(), 3)

        assert result["course_shortname"] == "ECON101"
        assert result["files"]
        assert result["bullets"]
        assert result["suggested_filename"] == "ECON101-week-3-study-pack.md"

        markdown = result["markdown"]
        _assert_provenance(markdown, site=DemoMoodleClient().base_url)
        assert "\n# ECON101: Week 3" in markdown
        assert "## Study notes" in markdown
        assert "## Materials" in markdown
        # Extracted demo content makes it into the pack body.
        assert "elasticity" in markdown.lower()
        for entry in result["files"]:
            assert entry["file_name"] in markdown

    def test_no_token_or_file_url_leak(self):
        client = DemoMoodleClient()
        result = build_study_pack(client, _econ_course_id(), 3)
        text = json.dumps(result).lower()
        assert "file_url" not in text
        assert "fileurl" not in text
        assert "wstoken" not in text
        assert "token=" not in result["markdown"].lower()

    def test_progress_callback(self):
        client = DemoMoodleClient()
        seen = []
        build_study_pack(client, _econ_course_id(), 3, on_file=seen.append)
        assert seen and all(name.endswith(".pdf") for name in seen)

    def test_unmatched_week_raises(self):
        client = DemoMoodleClient()
        # A week that matches no section must fail loudly rather than
        # fabricate a plausible pack from an unrelated section.
        with pytest.raises(WeekNotFoundError) as exc_info:
            build_study_pack(client, _econ_course_id(), "zzz_nonsense")
        exc = exc_info.value
        assert exc.week == "zzz_nonsense"
        assert "no section matching week 'zzz_nonsense'" in str(exc)
        assert "ECON101" in str(exc)
        # Available sections are offered to help the caller recover.
        assert any("Week 3" in name for name in exc.available_sections)

    def test_empty_but_valid_week_still_builds(self):
        client = DemoMoodleClient()
        # "revision" matches the empty "Revision and Exam Preparation"
        # section: a legitimate empty state, not a not-found error.
        result = build_study_pack(client, _econ_course_id(), "revision")
        assert "Revision" in result["section_name"]
        # Matched special-week section, so fallback notes rather than a raise.
        assert result["section_type"] in ("revision", "exam")
        assert result["bullets"]
        assert "_No downloadable materials" in result["markdown"]

    def test_includes_more_than_five_files(self):
        # The section helper's own default caps at 5; a pack must not
        # silently inherit that.
        result = build_study_pack(_ManyFilesClient(7), 1, 1)
        assert len(result["files"]) == 7
        assert not any("Including the first" in w for w in result["warnings"])

    def test_cap_beyond_max_files_warns(self):
        result = build_study_pack(_ManyFilesClient(10), 1, 1)
        assert len(result["files"]) == 8  # MAX_PACK_FILES
        assert any(
            "first 8 of 10 supported files" in w for w in result["warnings"]
        )

    def test_all_metadata_fields_sanitized(self):
        client = _ManyFilesClient(
            1, fullname="Testing 101 token=SECRET1234 edition",
        )
        result = build_study_pack(client, 1, 1)
        text = json.dumps(result)
        assert "SECRET1234" not in text
        assert f"token={REDACTED}" in result["course_fullname"]


class TestWriteStudyPack:
    def test_writes_utf8(self, tmp_path):
        path = write_study_pack("# T\n\nCafé — notes\n",
                                tmp_path, "pack.md")
        assert path.read_text(encoding="utf-8").startswith("# T")

    def test_never_overwrites(self, tmp_path):
        first = write_study_pack("one", tmp_path, "pack.md")
        second = write_study_pack("two", tmp_path, "pack.md")
        assert first != second
        assert first.read_text(encoding="utf-8") == "one"
        assert second.read_text(encoding="utf-8") == "two"

    def test_pack_file_is_created_owner_only(self, tmp_path, monkeypatch):
        """A pack holds a week's course material verbatim — 0600, and the
        mode is requested at creation (checkable on every platform).

        Two creations: the reserved placeholder that claims the name, and
        the temp file the content is written into before the rename.
        """
        modes = []
        real_open = os.open

        def spy(path, flags, mode=0o777, **kwargs):
            if flags & os.O_CREAT:  # ignore the read-only directory fsync
                modes.append(mode)
            return real_open(path, flags, mode, **kwargs)

        monkeypatch.setattr(secureio.os, "open", spy)
        write_study_pack("# T\n", tmp_path / "packs", "pack.md")
        assert modes == [0o600, 0o600]

    def test_placeholder_swapped_for_a_symlink_is_refused(
        self, tmp_path, monkeypatch,
    ):
        """The reservation claims a name; between then and the write it
        could be replaced with a link to somewhere else."""
        target = tmp_path / "victim.md"
        target.write_text("original", encoding="utf-8")
        real_reserve = studypack._reserve_path

        def swap(path):
            reserved = real_reserve(path)
            reserved.unlink()
            reserved.symlink_to(target)
            return reserved

        try:
            (tmp_path / "probe").symlink_to(target)
        except (OSError, NotImplementedError):
            pytest.skip("this environment cannot create symbolic links")
        monkeypatch.setattr(studypack, "_reserve_path", swap)
        with pytest.raises(SecureWriteError):
            write_study_pack("# leaked\n", tmp_path, "pack.md")
        assert target.read_text(encoding="utf-8") == "original"

    @pytest.mark.skipif(
        os.name == "nt", reason="POSIX permissions are not applicable on Windows"
    )
    def test_pack_file_mode_on_posix(self, tmp_path):
        path = write_study_pack("# T\n", tmp_path / "packs", "pack.md")
        assert stat.S_IMODE(path.stat().st_mode) == 0o600
        assert stat.S_IMODE((tmp_path / "packs").stat().st_mode) == 0o700


class TestCliSurface:
    def test_study_pack_writes_file(self, tmp_path, capsys):
        main(["--demo", "study-pack", "ECON101", "--week", "3",
              "--output", str(tmp_path), "-q"])
        out = capsys.readouterr().out
        assert "Study pack written to" in out
        written = list(tmp_path.glob("*.md"))
        assert len(written) == 1
        content = written[0].read_text(encoding="utf-8")
        _assert_provenance(content, site=DemoMoodleClient().base_url)
        assert "\n# ECON101: Week 3" in content

    def test_study_pack_stdout(self, capsys):
        main(["--demo", "study-pack", "ECON101", "--week", "3",
              "--stdout", "-q"])
        out = capsys.readouterr().out
        # The printed variant carries the same header as the written one:
        # a pack pasted somewhere else must still say what it is.
        _assert_provenance(out, site=DemoMoodleClient().base_url)
        assert "\n# ECON101: Week 3" in out

    def test_stdout_never_resolves_a_downloads_directory(
        self, tmp_path, monkeypatch, capsys,
    ):
        """--stdout writes nothing, so it warns about nothing.

        Resolving a destination is what reports a refused
        WORSAGA_DOWNLOADS_DIR, and a run that creates no file has no
        destination to report. Warning anyway would train the reader to
        ignore the warning in the case that matters.
        """
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("WORSAGA_DOWNLOADS_DIR", "packs-relative")
        main(["--demo", "study-pack", "ECON101", "--week", "3",
              "--stdout", "-q"])
        captured = capsys.readouterr()
        assert "WORSAGA_DOWNLOADS_DIR" not in captured.err
        assert "must be an absolute path" not in captured.err
        # The pack itself still came out.
        assert "\n# ECON101: Week 3" in captured.out

    def test_a_written_pack_resolves_its_destination_before_fetching(
        self, tmp_path, capsys,
    ):
        # The contrast, and the property the ordering exists for: a run
        # that does write a file resolves where it goes exactly once, and
        # before the week's downloads start.
        from worsaga import cli as cli_module

        with patch.object(cli_module, "_resolve_output_dir",
                          return_value=tmp_path) as resolve:
            main(["--demo", "study-pack", "ECON101", "--week", "3", "-q"])
        assert resolve.call_count == 1
        assert "Study pack written to" in capsys.readouterr().out

    def test_stdout_asks_for_no_destination_at_all(self, capsys):
        from worsaga import cli as cli_module

        with patch.object(cli_module, "_resolve_output_dir") as resolve:
            main(["--demo", "study-pack", "ECON101", "--week", "3",
                  "--stdout", "-q"])
        assert resolve.call_count == 0
        assert "\n# ECON101: Week 3" in capsys.readouterr().out

    def test_study_pack_json(self, tmp_path, capsys):
        main(["--demo", "--json", "study-pack", "ECON101", "--week", "3",
              "--output", str(tmp_path)])
        payload = json.loads(capsys.readouterr().out)
        assert "markdown" not in payload  # content lives in the file
        assert payload["path"].endswith(".md")
        assert payload["files"]
        text = json.dumps(payload).lower()
        assert "file_url" not in text
        assert "wstoken" not in text


class TestMcpSurface:
    def test_export_study_pack(self, tmp_path):
        from worsaga import mcp_server

        client = DemoMoodleClient()
        with patch.object(mcp_server, "_get_client", return_value=client), \
             patch.object(mcp_server, "default_downloads_dir",
                          return_value=tmp_path):
            result = mcp_server.export_study_pack(_econ_course_id(), "3")

        assert "error" not in result
        assert "markdown" not in result
        pack = tmp_path / result["path"].rsplit("\\", 1)[-1].rsplit("/", 1)[-1]
        assert pack.exists()
        _assert_provenance(
            pack.read_text(encoding="utf-8"), site=DemoMoodleClient().base_url,
        )

    def test_export_include_markdown(self, tmp_path):
        from worsaga import mcp_server

        client = DemoMoodleClient()
        with patch.object(mcp_server, "_get_client", return_value=client), \
             patch.object(mcp_server, "default_downloads_dir",
                          return_value=tmp_path):
            result = mcp_server.export_study_pack(
                _econ_course_id(), "3", include_markdown=True,
            )
        _assert_provenance(
            result["markdown"], site=DemoMoodleClient().base_url,
        )

    def test_export_rejects_escape(self, tmp_path):
        from worsaga import mcp_server

        client = DemoMoodleClient()
        with patch.object(mcp_server, "_get_client", return_value=client), \
             patch.object(mcp_server, "default_downloads_dir",
                          return_value=tmp_path):
            result = mcp_server.export_study_pack(
                _econ_course_id(), "3", output_dir="..",
            )
        assert result.get("error_code") == "invalid_output_dir"
